import type { AppData, DraftList, Place, TripList, User } from './types';

function place(id: string, name: string, address: string, lat: number, lng: number): Place {
  return { id, name, address, lat, lng };
}

export const demoUsers: User[] = [
  {
    id: 'u-maya',
    name: 'Maya Cohen',
    handle: '@mayawanders',
    city: 'Tel Aviv',
    bio: 'Builds routes around food stalls, hidden beaches, and long train rides.',
    avatar: 'MC',
    accent: 'linear-gradient(135deg, #f97316, #fb7185)',
  },
  {
    id: 'u-sofia',
    name: 'Sofia Park',
    handle: '@sofiaslowtravel',
    city: 'Seoul',
    bio: 'Slow city walks, museum lunches, and late-night dessert missions.',
    avatar: 'SP',
    accent: 'linear-gradient(135deg, #14b8a6, #0f766e)',
  },
  {
    id: 'u-noah',
    name: 'Noah Levin',
    handle: '@noahnotes',
    city: 'Lisbon',
    bio: 'Traces every trip by coffee stops, viewpoints, and ferry crossings.',
    avatar: 'NL',
    accent: 'linear-gradient(135deg, #2563eb, #7c3aed)',
  },
  {
    id: 'u-aya',
    name: 'Aya Idris',
    handle: '@ayaplaces',
    city: 'Marrakesh',
    bio: 'Curates color-rich routes built for markets, rooftops, and design hotels.',
    avatar: 'AI',
    accent: 'linear-gradient(135deg, #ea580c, #f43f5e)',
  },
];

export const demoLists: TripList[] = [
  {
    id: 'list-kyoto',
    ownerId: 'u-sofia',
    title: 'Kyoto after rain',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1200&auto=format&fit=crop',
    location: 'Kyoto',
    country: 'Japan',
    vibe: 'temples + tea houses',
    description: 'A compact route for peaceful mornings, old streets, and one perfect ramen stop.',
    places: [
      place('p-kyoto-1', 'Kiyomizu-dera', '1-294 Kiyomizu, Higashiyama Ward, Kyoto', 34.9949, 135.785),
      place('p-kyoto-2', 'Ninenzaka', 'Ninenzaka, Higashiyama Ward, Kyoto', 34.9959, 135.7788),
      place('p-kyoto-3', 'Nishiki Market', 'Nishikikoji-dori, Nakagyo Ward, Kyoto', 35.005, 135.7649),
      place('p-kyoto-4', 'Togetsukyo Bridge', 'Saga Tenryuji, Ukyo Ward, Kyoto', 35.0094, 135.6779),
    ],
    season: 'spring',
    budget: 'mid-range',
    createdAt: '2026-06-02T08:00:00.000Z',
  },
  {
    id: 'list-mexico',
    ownerId: 'u-maya',
    title: 'Mexico City taqueria loop',
    coverImage: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?q=80&w=1200&auto=format&fit=crop',
    location: 'Mexico City',
    country: 'Mexico',
    vibe: 'tacos + design hotels',
    description: 'A social-night route with museums by day and neighborhood taquerias at dusk.',
    places: [
      place('p-mex-1', 'Roma Norte', 'Roma Norte, Mexico City', 19.42, -99.1637),
      place('p-mex-2', 'Condesa', 'Condesa, Mexico City', 19.4108, -99.1706),
      place('p-mex-3', 'Mercado de Coyoacán', 'Ignacio Allende s/n, Coyoacán, Mexico City', 19.355, -99.1625),
      place('p-mex-4', 'Museo Jumex', 'Blvd. Miguel de Cervantes Saavedra, Mexico City', 19.4392, -99.2016),
    ],
    season: 'autumn',
    budget: 'mixed',
    createdAt: '2026-06-10T08:00:00.000Z',
  },
  {
    id: 'list-patagonia',
    ownerId: 'u-noah',
    title: 'Patagonia road reset',
    coverImage: 'https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?q=80&w=1200&auto=format&fit=crop',
    location: 'El Calafate',
    country: 'Argentina',
    vibe: 'glaciers + long drives',
    description: 'A wide-open trip list for lake viewpoints, rental cars, and windproof layers.',
    places: [
      place('p-pat-1', 'Perito Moreno Glacier', 'Los Glaciares National Park, Santa Cruz', -50.4967, -73.0501),
      place('p-pat-2', 'Lago Argentino', 'Lago Argentino, Santa Cruz', -50.38, -72.38),
      place('p-pat-3', 'Ruta 40 overlook', 'Ruta Nacional 40, Santa Cruz', -49.95, -71.55),
      place('p-pat-4', 'Estancia dinners', 'El Calafate, Santa Cruz', -50.25, -72.1),
    ],
    season: 'summer',
    budget: 'high',
    createdAt: '2026-06-15T08:00:00.000Z',
  },
  {
    id: 'list-lisbon',
    ownerId: 'u-aya',
    title: 'Lisbon tram and rooftop map',
    coverImage: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?q=80&w=1200&auto=format&fit=crop',
    location: 'Lisbon',
    country: 'Portugal',
    vibe: 'sunsets + petiscos',
    description: 'Built for tiled streets, ferry sunsets, and a rooftop dinner at golden hour.',
    places: [
      place('p-lis-1', 'Alfama', 'Alfama, Lisbon', 38.7139, -9.1301),
      place('p-lis-2', 'Miradouro de Santa Catarina', 'R. de Santa Catarina, Lisbon', 38.7095, -9.1477),
      place('p-lis-3', 'LX Factory', 'R. Rodrigues de Faria 103, Lisbon', 38.7028, -9.1778),
      place('p-lis-4', 'Cais do Sodré', 'Cais do Sodré, Lisbon', 38.7061, -9.1456),
    ],
    season: 'summer',
    budget: 'mid-range',
    createdAt: '2026-06-20T08:00:00.000Z',
  },
  {
    id: 'list-iceland',
    ownerId: 'u-sofia',
    title: 'Iceland ring road snippets',
    coverImage: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?q=80&w=1200&auto=format&fit=crop',
    location: 'Reykjavik',
    country: 'Iceland',
    vibe: 'waterfalls + hot springs',
    description: 'A flexible route of stops for short daylight windows and long horizon views.',
    places: [
      place('p-ice-1', 'Þingvellir National Park', 'Þingvellir, Iceland', 64.2559, -21.1295),
      place('p-ice-2', 'Blue Lagoon', 'Norðurljósavegur 9, Grindavík', 63.8804, -22.4495),
      place('p-ice-3', 'Reynisfjara black sand beach', 'Reynisfjara, Iceland', 63.4052, -19.0446),
      place('p-ice-4', 'Vík guesthouse dinners', 'Vík í Mýrdal, Iceland', 63.4186, -19.006),
    ],
    season: 'winter',
    budget: 'high',
    createdAt: '2026-06-25T08:00:00.000Z',
  },
];

export const demoData: AppData = {
  currentUserId: 'u-maya',
  users: demoUsers,
  lists: demoLists,
  ratings: [
    {
      id: 'rating-1',
      listId: 'list-kyoto',
      userId: 'u-maya',
      score: 5,
      createdAt: '2026-07-20T10:00:00.000Z',
    },
    {
      id: 'rating-2',
      listId: 'list-mexico',
      userId: 'u-sofia',
      score: 4,
      createdAt: '2026-07-22T09:15:00.000Z',
    },
    {
      id: 'rating-3',
      listId: 'list-lisbon',
      userId: 'u-maya',
      score: 5,
      createdAt: '2026-07-24T18:42:00.000Z',
    },
  ],
  follows: [
    { followerId: 'u-maya', followingId: 'u-sofia' },
    { followerId: 'u-maya', followingId: 'u-noah' },
    { followerId: 'u-sofia', followingId: 'u-aya' },
  ],
  savedLists: [
    { userId: 'u-maya', listId: 'list-kyoto' },
    { userId: 'u-maya', listId: 'list-lisbon' },
  ],
  likes: [
    { userId: 'u-maya', listId: 'list-kyoto' },
    { userId: 'u-sofia', listId: 'list-mexico' },
    { userId: 'u-noah', listId: 'list-mexico' },
    { userId: 'u-aya', listId: 'list-lisbon' },
    { userId: 'u-maya', listId: 'list-lisbon' },
  ],
};

export const emptyDraft: DraftList = {
  title: '',
  coverImage: '',
  location: '',
  country: '',
  vibe: '',
  description: '',
  places: [],
  season: 'summer',
  budget: 'mid-range',
};
